-- MySQL Script generated by MySQL Workbench
-- Wed Dec 27 00:55:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CullDampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CullDampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CullDampolla` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `CullDampolla` ;

-- -----------------------------------------------------
-- Table `CullDampolla`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CullDampolla`.`clientes` (
  `id_clientes` INT NOT NULL,
  `nombre` VARCHAR(160) NULL DEFAULT NULL,
  `direccion_cliente` VARCHAR(200) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `email_cliente` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_registro_cliente` TIMESTAMP NULL DEFAULT NULL,
  `id_recomendator` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CullDampolla`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CullDampolla`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `apellido` VARCHAR(90) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CullDampolla`.`provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CullDampolla`.`provedor` (
  `id_provedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(180) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `fax` TINYINT NULL DEFAULT NULL,
  `nif` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_provedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CullDampolla`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CullDampolla`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NULL DEFAULT NULL,
  `graduacion_vidros` TINYINT NULL DEFAULT NULL,
  `color_muntura` VARCHAR(15) NULL DEFAULT NULL,
  `color_vidrio` VARCHAR(15) NULL DEFAULT NULL,
  `precio` TINYINT NULL DEFAULT NULL,
  `provedor` INT NULL DEFAULT NULL,
  `empleado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `gafas_ibfk_1_idx` (`provedor` ASC) VISIBLE,
  INDEX `fk_gafas_empleado_idx` (`empleado` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `CullDampolla`.`empleado` (`id_empleado`),
  CONSTRAINT `fk_gafas_provedor`
    FOREIGN KEY (`provedor`)
    REFERENCES `CullDampolla`.`provedor` (`id_provedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
