services:
  mongodb:
    image: mongo
    container_name: mongoDB
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
