-- MySQL Script generated by MySQL Workbench
-- Tue Jan  2 23:15:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `Provincia` VARCHAR(100) NOT NULL,
  `Localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idProvincia`, `Localidad_idLocalidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NULL DEFAULT NULL,
  `Apellido` VARCHAR(90) NOT NULL,
  `NumeroTelefono` INT NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `Provincia_Localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Provincia_idProvincia`, `Provincia_Localidad_idLocalidad`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  UNIQUE INDEX `NumeroTelefono_UNIQUE` (`NumeroTelefono` ASC) VISIBLE,
  INDEX `fk_Cliente_Provincia1_idx` (`Provincia_idProvincia` ASC, `Provincia_Localidad_idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia` , `Provincia_Localidad_idLocalidad`)
    REFERENCES `pizzeria`.`Provincia` (`idProvincia` , `Localidad_idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `Localidad` VARCHAR(150) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `Provincia_Localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`, `Provincia_idProvincia`, `Provincia_Localidad_idLocalidad`),
  INDEX `fk_Localidad_Provincia1_idx` (`Provincia_idProvincia` ASC, `Provincia_Localidad_idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Localidad_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia` , `Provincia_Localidad_idLocalidad`)
    REFERENCES `pizzeria`.`Provincia` (`idProvincia` , `Localidad_idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzeria`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  `Apellido` VARCHAR(200) NOT NULL,
  `NIF` INT NOT NULL,
  `Telefono` INT NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME ,
  `Delivery` TINYINT NULL,
  `Cantidad` INT NULL,
  `PrecioTotal` INT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `Cliente_idCliente`),
  INDEX `fk_Pedidos_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `pizzeria`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `pizzeria`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Imagen` BLOB NULL,
  `Precio` DOUBLE NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Pedidos_idPedidos`, `Pedidos_Cliente_idCliente`),
  INDEX `fk_Producto_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_Cliente_idCliente`)
    REFERENCES `pizzeria`.`Pedidos` (`idPedidos` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(70) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Pedidos_idPedidos` INT NOT NULL,
  `Producto_Pedidos_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `Producto_idProducto`, `Producto_Pedidos_idPedidos`, `Producto_Pedidos_Cliente_idCliente`),
  INDEX `fk_Categoria_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Pedidos_idPedidos` ASC, `Producto_Pedidos_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Pedidos_idPedidos` , `Producto_Pedidos_Cliente_idCliente`)
    REFERENCES `pizzeria`.`Producto` (`idProducto` , `Pedidos_idPedidos` , `Pedidos_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Tienda` (
  `idTienda` INT NOT NULL AUTO_INCREMENT,
  `Empleado_idEmpleado` INT NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `Provincia_Localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idTienda`, `Empleado_idEmpleado`, `Provincia_idProvincia`, `Provincia_Localidad_idLocalidad`),
  INDEX `fk_Tienda_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Tienda_Provincia1_idx` (`Provincia_idProvincia` ASC, `Provincia_Localidad_idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Tienda_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `pizzeria`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia` , `Provincia_Localidad_idLocalidad`)
    REFERENCES `pizzeria`.`Provincia` (`idProvincia` , `Localidad_idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
